[Leaders]
[[Leaders.Leader]] # moveleader
    Persist   = true
    KeyStart  = "757365727461626C653A7573657231773937383833313437333137333731323135"
    KeyEnd    = "757365727461626C653A7573657234543637353232383738383832303830353737"   
    StartTime = "2019-08-05T07:30:00-08:00"
    EndTime   = "2019-08-16T10:30:00-08:00"
    [[Leaders.Leader.Stores]]
        [[Leaders.Leader.Stores.StoreLabel]]
            Key   = "zone"
            Value = "z4"
        [[Leaders.Leader.Stores.StoreLabel]]
            Key   = "rack"
            Value = "r4"
        [[Leaders.Leader.Stores.StoreLabel]]
            Key   = "host"
            Value = "h4"
    [[Leaders.Leader.Stores]]
        [[Leaders.Leader.Stores.StoreLabel]]
            Key   = "zone"
            Value = "z5"
        [[Leaders.Leader.Stores.StoreLabel]]
            Key   = "rack"
            Value = "r5"
        [[Leaders.Leader.Stores.StoreLabel]]
            Key   = "host"
            Value = "h5"
[[Leaders.Leader]] # moveleader
    Persist   = true
    KeyStart  = "757365727461626C653A7573657234543637353232383738383832303830353737"
    KeyEnd    = "757365727461626C653A7573657236343637353232383738383832303830353737"   
    StartTime = "2019-08-05T07:30:00-08:00"
    EndTime   = "2019-08-16T10:30:00-08:00"
    [[Leaders.Leader.Stores]]
        [[Leaders.Leader.Stores.StoreLabel]]
            Key   = "zone"
            Value = "z2"
        [[Leaders.Leader.Stores.StoreLabel]]
            Key   = "rack"
            Value = "r2"
        [[Leaders.Leader.Stores.StoreLabel]]
            Key   = "host"
            Value = "h2"

[Regions]
[[Regions.Region]] # moveregion
    Persist   = true
    KeyStart  = "757365727461626C653A7573657236343637353232383738383832303830353737"
    KeyEnd    = "757365727461626C653A7573657238173036373639353831393732343031333937"
    StartTime = "2019-08-05T07:30:00-08:00"
    EndTime   = "2019-08-16T10:30:00-08:00"
    [[Regions.Region.Stores]]
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "zone"
            Value = "z1"
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "rack"
            Value = "r1"
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "host"
            Value = "h1"
    [[Regions.Region.Stores]]
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "zone"
            Value = "z2"
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "rack"
            Value = "r2"
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "host"
            Value = "h2"
    [[Regions.Region.Stores]]
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "zone"
            Value = "z3"
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "rack"
            Value = "r3"
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "host"
            Value = "h3"
[[Regions.Region]] # moveregion
    Persist   = true
    KeyStart  = "757365727461626C653A7573657238173036373639353831393732343031333937"
    KeyEnd    = "757365727461626C653A7573657239973036373639353831393732343031333937"
    StartTime = "2019-08-05T07:30:00-08:00"
    EndTime   = "2019-08-16T10:30:00-08:00"
    [[Regions.Region.Stores]]
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "zone"
            Value = "z4"
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "rack"
            Value = "r4"
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "host"
            Value = "h4"
    [[Regions.Region.Stores]]
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "zone"
            Value = "z5"
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "rack"
            Value = "r5"
        [[Regions.Region.Stores.StoreLabel]]
            Key   = "host"
            Value = "h5"
